baseurl = "/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Andy Winarko"
title = "~/.andy_winarko"
disqusshortname = "winarkoandy"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
titlestyle = "lowercase"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = ""
copyright = "Copyright © 2019 Andy Winarko"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/terminal-small.png"
faviconfile = "img/terminal-small.png"
highlightjs = true
progressively = true
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
github = "winarcooo"
email = "winarcooo@gmail.com"
linkedin = "andywinarko"
facebook = "masAndywinarko"
social_banner = "img/terminal-small.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"